### ISSUE TITLE
squiny lechery dumb me squabble squabble squabble squabble 

### ISSUE THREAD

**Issue by pannous** [tokestermw/tensorflow-shakespeare#2]
Hi nice project!
How many epochs does it have to run before it produces anything 'useful'?
Willst thou provide a check point of your model?
Cheers!

**Comment by tokestermw** [comment]
https://s3-us-west-2.amazonaws.com/tensorflow-shakespeare/example/checkpoint

https://s3-us-west-2.amazonaws.com/tensorflow-shakespeare/example/translate.ckpt-10400

**Comment by pannous** [comment]
Thx!!
