### ISSUE TITLE
training data error

### ISSUE THREAD

**Issue by dogegg250** [tokestermw/tensorflow-shakespeare#3]
for aligned_data in DATA_LINKS:
        for root, dirs, filenames in os.walk(get_dir(aligned_data)):
           
          #you should sort filnames here, or they wouldn't match
 
            for filename in filenames:
                with open(os.path.join(get_dir(aligned_data), filename), 'r') as f:

**Comment by tokestermw** [comment]
Thanks changed here.

https://github.com/tokestermw/tensorflow-shakespeare/commit/9d80fd6b20f50c09c9b529c5950fe2f4efbe74fb
